### PR TITLE
Correct CMSTenuredPoolParser

### PR DESCRIPTION
**Pull request by loyispa**
Fix https://github.com/microsoft/gctoolkit/issues/319

### CODE REVIEW

**Comment by kcpeppe** [comment]
great catch!

**Comment by karianna** [comment]
@kcpeppe did you mean to close this as oppose to merging it?

**Comment by kcpeppe** [comment]
Issue was fixed so I think merge is the right thing to do.

**Comment by loyispa** [comment]
@kcpeppe   Did you mean that you would submit another pr to fix it?  Or it doesn't need to be fixed?

**Comment by loyispa** [comment]
Please notice that this pr was not  merged but **closed** :)

**Comment by karianna** [comment]
merged it now

**Pull request merged**
