### PR TITLE
bump version of gctoolkit-testdata dependency to 1.0.2

### PR DESCRIPTION
**Pull request by CRY0NE3**
Update version

### CODE REVIEW

**Comment by karianna** [comment]
@dsgrieve I'll let you merge if you're happy with it

**Comment by dsgrieve** [comment]
@CRY0NE3 Is this different than PR #18 ?

**Comment by CRY0NE3** [comment]
> Update version

G = 59923FBC

**Comment by dsgrieve** [comment]
No diffs from main.

**Comment by CRY0NE3** [comment]
Again, i was searching for the word Monero, and i end up here only to be denied.
Yes i am receiving all these codes, but how will i ever understand all these things without any suppprt? i dont how you all do it..but i find stupid you are all able to trust these CORRUPT NETWORKS that i am surrounded with..expect a single person can fix the GLOBAL PANDEMIC that CHINA AND ITS ALLIES scattered, and I by myself rely on codes to FIX it...without KNOWING who i am CONNECTING TO?

**Comment by karianna** [comment]
Suspect this is a bot, user has been reported to GH

**Comment by brunoborges** [comment]
@karianna you should be able to delete the comment, no?

**Comment by karianna** [comment]
Yes, but GH Abuse team wanted it left there to investigate.

**Pull request closed without merging**
